/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ac.daffodil.l4dc1000030.budgets.gui;

import ac.daffodil.l4dc1000030.budgets.manager.ScheduleDataManager;



public class MainUI extends javax.swing.JFrame {

    
    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        
        ScheduleDataManager.addScheduledTransactions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        transactionsMenuItem = new javax.swing.JMenuItem();
        scheduleMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        transferMenuItem = new javax.swing.JMenuItem();
        accountsMenuItem = new javax.swing.JMenuItem();
        categoryMenuItem = new javax.swing.JMenuItem();
        userManagementMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        transactionsMenuItem.setText("Transactions");
        transactionsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionsMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(transactionsMenuItem);

        scheduleMenuItem.setText("Schedule");
        scheduleMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(scheduleMenuItem);

        jMenuItem1.setText("UserAccount");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem1);

        transferMenuItem.setText("Transfer");
        transferMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(transferMenuItem);

        accountsMenuItem.setText("Accounts");
        accountsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountsMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(accountsMenuItem);

        categoryMenuItem.setText("Category");
        categoryMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(categoryMenuItem);

        userManagementMenuItem.setText("User Management");
        userManagementMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userManagementMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(userManagementMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1037, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void userManagementMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userManagementMenuItemActionPerformed
           
       UserUI userUi = new UserUI();
       desktopPane.add(userUi);
       userUi.setVisible(true);
    }//GEN-LAST:event_userManagementMenuItemActionPerformed

    private void transactionsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionsMenuItemActionPerformed
        TransactionUI transUI = new TransactionUI();
        desktopPane.add(transUI);
       transUI.setVisible(true);
    }//GEN-LAST:event_transactionsMenuItemActionPerformed

    private void categoryMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryMenuItemActionPerformed
        CategoryUI catagoryUI = new CategoryUI();
        desktopPane.add(catagoryUI);
       catagoryUI.setVisible(true);
    }//GEN-LAST:event_categoryMenuItemActionPerformed

    private void accountsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountsMenuItemActionPerformed
    AccountsUI accUI = new AccountsUI();
    desktopPane.add(accUI);
       accUI.setVisible(true);
    }//GEN-LAST:event_accountsMenuItemActionPerformed

    private void transferMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferMenuItemActionPerformed
       TransferUI tranui = new TransferUI();
    desktopPane.add(tranui);
       tranui.setVisible(true);
    }//GEN-LAST:event_transferMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      UserAccountUI uaui = new UserAccountUI();
      desktopPane.add(uaui);
       uaui.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void scheduleMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleMenuItemActionPerformed
       ScheduleUI schedule = new ScheduleUI();
       desktopPane.add(schedule);
       schedule.setVisible(true);
    }//GEN-LAST:event_scheduleMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem accountsMenuItem;
    private javax.swing.JMenuItem categoryMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem scheduleMenuItem;
    private javax.swing.JMenuItem transactionsMenuItem;
    private javax.swing.JMenuItem transferMenuItem;
    private javax.swing.JMenuItem userManagementMenuItem;
    // End of variables declaration//GEN-END:variables

}
