/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ac.daffodil.l4dc1000030.budgets.gui;



import ac.daffodil.l4dc1000030.budgets.beans.Accounts;
import ac.daffodil.l4dc1000030.budgets.beans.Transfer;
import ac.daffodil.l4dc1000030.budgets.gui.table.TransferTableModel;
import ac.daffodil.l4dc1000030.budgets.manager.AccountsDataManager;
import java.util.ArrayList;
import java.util.UUID;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;





public class TransferUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form TransferUI
     */
    public TransferUI() {
        initComponents();
        
        loadFromAccountName();
        loadToAccountName();
        
        transferDetailsTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {

                int selectedRow = transferDetailsTable.getSelectedRow();
                if (selectedRow >= 0) {
                    Transfer transfer = transferTableModel.getTransferDetails(selectedRow);
                    if (transfer != null) {
                        amountField.setText(String.valueOf(transfer.getAmount()));
                        accountFromComboBox.setSelectedItem(transfer.getFromAccount()); // CHANGE from transfer class 
                        accountToComboBox.setSelectedItem(transfer.getToAccount());
                        jDateChooser1.setDate(transfer.getTransferDate());

                    }
                }
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateLabel = new javax.swing.JLabel();
        fromLabel = new javax.swing.JLabel();
        accountFromComboBox = new javax.swing.JComboBox<>();
        toLabel = new javax.swing.JLabel();
        accountToComboBox = new javax.swing.JComboBox<>();
        amountLabel = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        OKButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        transferTableModel = new TransferTableModel();
        transferDetailsTable = new javax.swing.JTable();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Transfer UI");

        dateLabel.setText("Date :");

        fromLabel.setText("From :");

        toLabel.setText("To :");

        amountLabel.setText("Amount : ");

        OKButton.setText("Create");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        transferDetailsTable.setModel(transferTableModel);
        jScrollPane1.setViewportView(transferDetailsTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(71, 71, 71)
                                    .addComponent(dateLabel))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fromLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(toLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(amountLabel, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(accountFromComboBox, 0, 393, Short.MAX_VALUE)
                                .addComponent(accountToComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(amountField)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(OKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(updateButton)
                        .addGap(66, 66, 66)
                        .addComponent(deleteButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountFromComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fromLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountToComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(updateButton)
                    .addComponent(OKButton))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        Transfer transfer  = new Transfer();
       transfer.setId(UUID.randomUUID().toString());
               transfer.setFromAccount((Accounts) accountFromComboBox.getSelectedItem());
              transfer.setToAccount((Accounts) accountToComboBox.getSelectedItem());
              transfer.setTransferDate(jDateChooser1.getDate());
              transfer.setAmount(Double.parseDouble(amountField.getText()));
              
               
               transferTableModel.addRow(transfer);
               JOptionPane.showMessageDialog(this, " You have successfully transferred credit to your desired account!");
    }//GEN-LAST:event_OKButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
    int selectedRow = transferDetailsTable.getSelectedRow();
        if(selectedRow  >= 0){
            
          Transfer transfer  = transferTableModel.getTransferDetails(selectedRow);
   
               transfer.setFromAccount((Accounts) accountFromComboBox.getSelectedItem());
              transfer.setToAccount((Accounts) accountToComboBox.getSelectedItem());
              //transfer.setTransferDate(transferDateField.getDate());
              transfer.setAmount(Double.parseDouble(amountField.getText()));
              
               
               transferTableModel.updateRow(selectedRow, transfer);
               
        
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
      int  selectedRow = transferDetailsTable.getSelectedRow();
       if(selectedRow>=0){
           transferTableModel.deleteRow(selectedRow);
          
           
       }else{
           JOptionPane.showMessageDialog(this, "Please select a row first");
       }
    }//GEN-LAST:event_deleteButtonActionPerformed

    
    private void loadFromAccountName() {
        ArrayList<Accounts> accList = AccountsDataManager.load(); // change class name and import
        accountFromComboBox.removeAllItems();

        if (accList != null) {
            for (int i = 0; i < accList.size(); i++) {
                accountFromComboBox.addItem(accList.get(i));
            }
        }
    }
    
    private void loadToAccountName(){
        ArrayList<Accounts> accList = AccountsDataManager.load();
        accountToComboBox.removeAllItems();
        
        if (accList !=null){
            for(int i = 0; i<accList.size(); i++){
                accountToComboBox.addItem(accList.get(i));
            }
                
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKButton;
    private javax.swing.JComboBox<Accounts> accountFromComboBox;
    private javax.swing.JComboBox<Accounts> accountToComboBox;
    private javax.swing.JTextField amountField;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel fromLabel;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel toLabel;
    private javax.swing.JTable transferDetailsTable;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
TransferTableModel transferTableModel;
}
