/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ac.daffodil.l4dc1000030.budgets.gui;


import ac.daffodil.l4dc1000030.budgets.beans.Accounts;
import ac.daffodil.l4dc1000030.budgets.beans.Category;
import ac.daffodil.l4dc1000030.budgets.beans.Transaction;
import ac.daffodil.l4dc1000030.budgets.gui.table.TransactionTableModel;
import ac.daffodil.l4dc1000030.budgets.manager.AccountsDataManager;
import ac.daffodil.l4dc1000030.budgets.manager.CategoryDataManager;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;


public class TransactionUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form TransectionUI
     */
    public TransactionUI() {
        initComponents();
         loadAccounts();
         loadCategory();
    
         netFlowofMoneyField.setText(String.valueOf(transectionTableModel.getTotal()));
    
         transactionTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {

                int selectedRow = transactionTable.getSelectedRow();
                if (selectedRow >= 0) {
                    Transaction transaction = transectionTableModel.getTransaction(selectedRow);
                    if (transaction != null) {

                        
                        jDateChooser1.setDate(transaction.getDate());
                        categoryOfTransactionComboBox.setSelectedItem(transaction.getAccount());
                        sourceAccountsComboBox.setSelectedItem(transaction.getCategory());
                        payeeTextField.setText(transaction.getPayee());

                    }
                }

            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        amountLabel = new javax.swing.JLabel();
        amountTextField = new javax.swing.JTextField();
        catagoryLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        dateLabel = new javax.swing.JLabel();
        sourceOfIncomeLabel = new javax.swing.JLabel();
        sourceOfIncomeField = new javax.swing.JTextField();
        sourceaccountLabel = new javax.swing.JLabel();
        modeOfTransactionLabel = new javax.swing.JLabel();
        netFlowofMoneyLabel = new javax.swing.JLabel();
        hystoryLabel = new javax.swing.JLabel();
        netFlowofMoneyField = new javax.swing.JTextField();
        categoryOfTransactionComboBox = new javax.swing.JComboBox<>();
        sourceAccountsComboBox = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        payeeLabel = new javax.swing.JLabel();
        payeeTextField = new javax.swing.JTextField();
        modeOfTransactionComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        transectionTableModel = new TransactionTableModel();
        transactionTable = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);

        amountLabel.setText("Transaction Amount : ");

        catagoryLabel.setText("Category of Transaction");

        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteButton)
                    .addComponent(updateButton)
                    .addComponent(addButton))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addButton)
                .addGap(18, 18, 18)
                .addComponent(updateButton)
                .addGap(28, 28, 28)
                .addComponent(deleteButton)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        dateLabel.setText("Date");

        sourceOfIncomeLabel.setText("Source Of Income");

        sourceaccountLabel.setText("Source Account");

        modeOfTransactionLabel.setText("Mode of Transaction");

        netFlowofMoneyLabel.setText("Net Flow of Money");

        hystoryLabel.setText("Hystory/Activity");

        payeeLabel.setText("Payee");

        modeOfTransactionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Credit Card" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(amountLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(dateLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(catagoryLabel)
                            .addComponent(sourceaccountLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sourceOfIncomeLabel)
                                    .addComponent(payeeLabel))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(payeeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sourceOfIncomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sourceAccountsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(categoryOfTransactionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(netFlowofMoneyLabel)
                                    .addComponent(hystoryLabel)
                                    .addComponent(modeOfTransactionLabel))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(netFlowofMoneyField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(modeOfTransactionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateLabel)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(amountLabel)
                            .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(catagoryLabel)
                            .addComponent(categoryOfTransactionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sourceaccountLabel)
                            .addComponent(sourceAccountsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sourceOfIncomeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sourceOfIncomeField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(payeeLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(payeeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modeOfTransactionLabel)
                    .addComponent(modeOfTransactionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(netFlowofMoneyLabel)
                    .addComponent(netFlowofMoneyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(hystoryLabel)
                .addGap(6, 6, 6))
        );

        transactionTable.setModel(transectionTableModel);
        jScrollPane1.setViewportView(transactionTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        Transaction  transaction = new Transaction();

        transaction.setAmount(Integer.parseInt(amountTextField.getText()));
   //add to other combo boxes//
   transaction.setModeOfTransaction((String)modeOfTransactionComboBox.getSelectedItem());
    transaction.setNetFlowOfMoney(netFlowofMoneyField.getText());
        transaction.setCategory((Category)categoryOfTransactionComboBox.getSelectedItem());
        transaction.setAccount((Accounts) sourceAccountsComboBox.getSelectedItem());
        transaction.setPayee(payeeTextField.getText());
        transaction.setDate(jDateChooser1.getDate());
        transectionTableModel.addRow(transaction);
        netFlowofMoneyField.setText(String.valueOf(transectionTableModel.getTotal()));
    }//GEN-LAST:event_addButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        int selectedRow = transactionTable.getSelectedRow();
        if(selectedRow>=0){
            Transaction transaction = new Transaction();

            transaction.setAmount(Integer.parseInt(amountTextField.getText()));
   //add to other combo boxes//
   transaction.setModeOfTransaction((String)modeOfTransactionComboBox.getSelectedItem());
    transaction.setNetFlowOfMoney(netFlowofMoneyField.getText());
        transaction.setCategory((Category)categoryOfTransactionComboBox.getSelectedItem());
        transaction.setAccount((Accounts) sourceAccountsComboBox.getSelectedItem());
        transaction.setPayee(payeeTextField.getText());
        transaction.setDate(jDateChooser1.getDate());

            transectionTableModel.updateRow(selectedRow, transaction);
            netFlowofMoneyField.setText(String.valueOf(transectionTableModel.getTotal()));
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int selectedRow = transactionTable.getSelectedRow();
        if(selectedRow>=0){
            Transaction transaction = transectionTableModel.getTransaction(selectedRow);
            transectionTableModel.deleteRow(selectedRow);
        }else{
            JOptionPane.showMessageDialog(this, "Please select a row first");

        }
    }//GEN-LAST:event_deleteButtonActionPerformed

private void loadAccounts(){
    ArrayList<Accounts> accList = AccountsDataManager.getUserAccountList();
    sourceAccountsComboBox.removeAllItems();
    
    if( accList != null){
        for( int i=0; i< accList.size();i++){
            sourceAccountsComboBox.addItem(accList.get(i));
        }
        
    }
    
}

private void loadCategory(){
    ArrayList<Category> categoryList = CategoryDataManager.load();
    categoryOfTransactionComboBox.removeAllItems();
    
    if (categoryList != null){
        for( int i=0; i < categoryList.size(); i++){
            categoryOfTransactionComboBox.addItem(categoryList.get(i));
        }
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JTextField amountTextField;
    private javax.swing.JLabel catagoryLabel;
    private javax.swing.JComboBox<Category> categoryOfTransactionComboBox;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel hystoryLabel;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> modeOfTransactionComboBox;
    private javax.swing.JLabel modeOfTransactionLabel;
    private javax.swing.JTextField netFlowofMoneyField;
    private javax.swing.JLabel netFlowofMoneyLabel;
    private javax.swing.JLabel payeeLabel;
    private javax.swing.JTextField payeeTextField;
    private javax.swing.JComboBox<Accounts> sourceAccountsComboBox;
    private javax.swing.JTextField sourceOfIncomeField;
    private javax.swing.JLabel sourceOfIncomeLabel;
    private javax.swing.JLabel sourceaccountLabel;
    private javax.swing.JTable transactionTable;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
private TransactionTableModel transectionTableModel;
}
